### ISSUE TITLE
Web components investigation (Spike)

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#209]
Technology spike to investigate the viability of using web components in our design system UI-libraries.

_Using drop-down component for investigation._

**Tasks**

- [x] Working React version
- [x] Working Angular version  
- [ ] [Passes an accessibility baseline](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html) [Use confluence docs as guide](https://goa-dio.atlassian.net/wiki/spaces/DIO/pages/1702690950/Accessibility)
