### ISSUE TITLE
 QA: Write Automated Tests for previous Input issues

### ISSUE THREAD

**Issue by lizhuomeng71** [GovAlta/ui-components#2094]
## Acceptance Criteria:

Automated tests are written for the following stories:

- [x] #1867
- [x] #1796
- [ ] #1703 (question about on Key Up)
- [x] #2089
- [x] #1598
- [x] #1577
- [x] #1532
- [ ] #1499 (some input does not have icon)
- [x] #1453

- [x] #1380 (this is not working for react, date type will load)
- [x] #1308
- [x] #1276
- [ ] #1220
- [x] #1149

- [x] #976

-----------------
Reviewed and decide not to automate
- [x] #1696 (This bug was dropped)
- [x] #1419 (Doc issue, not automated)
- [x] #885 (Not Possible to happen again, char count is moved inside text area, not automated)
- [x] #770 (Minor Stylying issue, not automated)
- [x] #503 (Cant Simulate mouse wheel, and for cypress built in browser, mouse wheel change number is not supported)
- [x] #492 (This is duplicate of 1598)
- [x] #1373 (this issue is still open)
- [x] #1455 (issue closed as no bug)
- [x] #738 (this tag no longer exist)
- [x] #1082  (this tag no longer exist)
- [x] #1140 (this tag no longer exist)
- [x] #1219 (this issue is still open)

**Comment by ArakTaiRoth** [comment]
Closing as this work is done now
