### ISSUE TITLE
Create roadmap for design system team work

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#250]
## Overview ##

The roadmap will communicate high-level vision for the process of design, development, delivery, and evolution of the design system.

As we look to get teams more involved in using and contributing to the design system it will be more important for us to be transparent about our plans.

## Acceptance criteria ##

**Roadmap planning session**
[Steps to roadmapping](https://www.nngroup.com/articles/roadmapping-steps/)

**The roadmap must address the following foundational questions:**
- [x] Define what the design system is
- [x] Define what the design system does
- [x] Where are we now? 
- [x] Where do we want to go?
- [x] How can we get there?
