### ISSUE TITLE
As a service team developer I want to understand how to use the ui-components in my service so I can leverage those components in my work

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#329]
**Context**
As we get closer to an initial launch of the ui-components communicating where they are, what's new, and how to use them will become quite important. As part of the release of the ui-components we want to ensure that the consumers of those components have a good understanding of what is in the library and how to use it. 

**Problem**
We are right at the start of getting a design system website launched and this site may be too immature to host this information. In a different vein, confluence has expanded to a point where finding what is needed at any given point can be quite a challenge.

**Tasks**

- [ ] Understand (from the service team developer perspective) what they expect from the ui-components documentation.
- [ ] Create a documentation prototype (based on service team developer feedback) to test with.
- [ ] Conduct usability testing to developer documentation (link to issue other issue)
