### ISSUE TITLE
Get NX linking the libraries properly.

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#341]
Background
The issue is that right now the libraries within the NX project are not properly linking up to each other as one would expect. Works well for approx 90% of the cases. Our web components

There are syncing issues

Watching the files but not the compiled files.

**Task**
- [ ] Get NX expert time to help investigate
- [ ] Connect with @chrisolsen to work through the solution

Linked to #223 

**What needs to be fixed**

- [ ] Allow all storybook files to auto refresh with the current version of the web-components
- [x] Fix the css variables not being included in the demo apps (the imports exist, but the values are not available)
- [ ] Fix the vue-components failing to build (...not really nx's fault on this one, just something that needs to be done) (remove)
- [ ] Currently in the `tsconfig.base.json` file the `styles` and `web-components` refer to the `dist` path (only way I could get things to work), determine if there is a better way to do this.

**Comment by chrisolsen** [comment]
**What needs to be fixed**

- [ ] Allow all storybook files to auto refresh with the current version of the web-components
- [ ] Fix the css variables not being included in the demo apps (the imports exist, but the values are not available)
- [ ] Fix the vue-components failing to build (...not really nx's fault on this one, just something that needs to be done)

**Comment by Spark450** [comment]
Libraries are linked and working.
