### ISSUE TITLE
Investigate Zenhub for managing sprints better including bug tracking

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#406]
**As a:** Contributor on the design system team
**I want:** The work tracking process/tools to be improved
**so that:** The team can represent the work more accurately and communicate status and progress better within and outside of the team.

### Acceptance criteria
- [ ] Investigate Zenhubs capabilities to enhance the design system teams operations
- [ ] Understand how the pricing model applies in our context
- [ ] Complete an [evaluation](https://miro.com/app/board/uXjVOL1IWro=/?invite_link_id=755875331286) on Zenhub that can be shared back with the team

### Presentable outcomes
N/A

### Resources:
**Mockups:** *[If applicable a URL to or the name of the mockup(s)]*
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by Spark450** [comment]
This would need to be configured by the GitHub account holders and could potentially have negative effects for other repos under GovAlta

Wil not do.
